### ISSUE TITLE
running on no display environment

### ISSUE THREAD

**Issue by syinari0123** [musyoku/generative-query-network#10]
Thank you for this repository.

When I tried to run this code on the no display environment (like EC2 server), I got following error.
```
Error 65544: X11: The DISPLAY environment variable is missing
Traceback (most recent call last):
  File "create_dataset.py", line 106, in <module>
    main()
  File "create_dataset.py", line 32, in main
    renderer = gqn.three.Renderer(screen_size[0], screen_size[1])
RuntimeError: Failed to initialize GLFW.
```
Currently this ```three.Renderer``` library seems to be coded in order to work on the display environment.
So please tell me how to modify this code for no display environment, if you know.

Regards, 
syinari0123

**Comment by syinari0123** [comment]
Sorry, I didn't know the same issue (https://github.com/musyoku/generative-query-network/issues/6) has already opened, so close this issue.
