### ISSUE TITLE
Failed to compile vertex shader

### ISSUE THREAD

**Issue by fengziyue** [musyoku/generative-query-network#5]
Hello @musyoku 
when I run create_dataset.py in "run/rooms" , there are some errors:
`/Desktop/generative-query-network-master/generative_query_network/run/rooms$ python3 create_dataset.py 
Error 65544: X11: RandR gamma ramp support seems broken
Failed to compile vertex shader
0:2(10): error: GLSL 4.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.50, 3.30, 1.00 ES, and 3.00 ES

Traceback (most recent call last):
  File "create_dataset.py", line 106, in <module>
    main()
  File "create_dataset.py", line 32, in main
    renderer = gqn.three.Renderer(screen_size[0], screen_size[1])
RuntimeError
`
My OS is Ubuntu16.04
is this error related to the NVIDIA driver?
my NVIDIA driver seems to have some problem

**Comment by musyoku** [comment]
The required OpenGL version is 4.5. 
Which GPU are you using?

**Comment by fengziyue** [comment]
GTX1080

**Comment by musyoku** [comment]
Please upgrade your OpenGL version.
